apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.16.1
    helm:
      values: |
        expose:
          type: ingress
          ingress:
            hosts:
              core: registry.bencoepp.de
            annotations:
              kubernetes.io/ingress.class: nginx
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              storageClass: standard
              size: 10Gi
        harborAdminPassword: "start#123"
        database:
          type: internal
          internal:
            password: "start#123"
        redis:
          type: internal
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true