stages:
  - test
  - deploy

test-job:
  stage: test
  image: python:3.9
  before_script:
    - python -m pip install --upgrade pip
    - pip install ansible
    - pip install distlib
    - pip install -r requirements.txt
  script:
    - ansible --version
    - ansible-galaxy install -r requirements.yml
    - echo "Tests completed successfully."

deploy:
  stage: deploy
  image: python:3.9
  environment:
    name: production
  before_script:
    - python -m pip install --upgrade pip
    - pip install ansible
    - pip install distlib
    - pip install -r requirements.txt
    - ansible-galaxy install -r requirements.yml
  script:
    - echo "$SSH_KEY" > id_rsa
    - chmod 400 id_rsa
    - echo "$HOSTS" > hosts.ini
    - ansible -m ping all -i hosts.ini -user root --private-key id_rsa
    - ansible-playbook -i hosts.ini setup.yml --become --become-user=root --private-key id_rsa