stages:
  - deploy

deploy-job:
  stage: deploy
  image: python:3.9
  environment: production
  before_script:
    - python -m pip install --upgrade pip
    - pip install ansible
    - ansible-galaxy install -r requirements.yml
  script:
    - echo "$SSH_KEY" > id_rsa
    - chmod 600 id_rsa
    - echo "$HOSTS" > hosts.yaml
    - ansible-playbook -i hosts.yaml setup.yml --private-key=id_rsa