stages:
  - test
  - deploy

test-reachable-job:
  stage: test
  image: python:3.10.16
  before_script:
    - python -m pip install --upgrade pip
    - pip install ansible
    - pip install "ansible-core>=2.16.4,<2.17.0"
    - pip install distlib
    - pip install -r requirements.txt
  script:
    - ansible --version
    - echo "$SSH_KEY" > bcp-cluster
    - chmod 400 bcp-cluster
    - echo "$HOSTS" > hosts.ini
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible -m ping all -i hosts.ini --user root --private-key bcp-cluster

test-job:
  stage: test
  image: python:3.10.16
  before_script:
    - python -m pip install --upgrade pip
    - pip install ansible
    - pip install "ansible-core>=2.16.4,<2.17.0"
    - pip install distlib
    - pip install -r requirements.txt
  script:
    - ansible --version
    - ansible-galaxy install -r requirements.yml
    - echo "Tests completed successfully."

deploy:
  stage: deploy
  image: python:3.10.16
  environment:
    name: production
  before_script:
    - python -m pip install --upgrade pip
    - pip install ansible
    - pip install "ansible-core>=2.16.4,<2.17.0"
    - pip install distlib
    - pip install -r requirements.txt
    - ansible-galaxy install -r requirements.yml
  script:
    - echo "$SSH_KEY" > ~/.ssh/bcp-cluster
    - chmod 400 ~/.ssh/bcp-cluster
    - echo "$HOSTS" > hosts.ini
    - ansible -m ping all -i hosts.ini --user root --private-key ~/.ssh/bcp-cluster
    - ansible-playbook -i hosts.ini setup.yml --become --become-user=root --private-key ~/.ssh/bcp-cluster