stages:
  - test
  - deploy

test-job:
  stage: test
  image: python:3.9
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - ansible -v
    - ansible-galaxy install -r requirements.yml

deploy:
  stage: deploy
  image: python:3.9
  environment: production
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - ansible-galaxy install -r requirements.yml
  script:
    - echo "$SSH_KEY" > id_rsa
    - chmod 600 id_rsa
    - echo "$HOSTS" > hosts.ini
    - ansible-playbook -i hosts.ini setup.yml --become --become-user=root --private-key=id_rsa