---
- name: Fetch Kube config from the first host in inventory
  hosts: "{{ groups['kube_control_plane'][0] }}"
  gather_facts: false

  tasks:
    - name: Fetch .kube/config
      fetch:
        src: .kube/config
        dest: kube_config
        flat: yes