---
- name: "Setup Kubernetes Cluster"
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install Kubernetes
      ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster