---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.16.1
    helm:
      parameters:
        - name: expose.ingress.hosts.core
          value: 'registry.bencoepp.de'
        - name: expose.ingress.className
          value: 'nginx'
        - name: expose.ingress.annotations."cert-manager.io/cluster-issuer"
          value: "letsencrypt-prod"
        - name: expose.ingress.annotations."nginx.ingress.kubernetes.io/ssl-passthrough"
          value: "true"
        - name: expose.ingress.annotations."nginx.ingress.kubernetes.io/backend-protocol"
          value: "HTTPS"
        - name: externalURL
          value: 'https://registry.bencoepp.de'
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true