---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.16.1
    helm:
      values: |
        expose:
          type: ingress
          ingress:
            hosts:
              core: registry.bencoepp.de
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
                  nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                  nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            tls:
              - secretName: harbor-tls # Replace with your TLS secret
                hosts:
                  - registry.bencoepp.de
        harborAdminPassword: "your-secure-password" # Replace with a secure password
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true