apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kyverno.github.io/kyverno/'
    targetRevision: 3.3.4
    chart: kyverno
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
