apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://charts.jetstack.io
  name: cert-manager
  type: helm