apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-operator
  namespace: argocd
spec:
  destination:
    namespace: rook
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.rook.io/release'
    targetRevision: v1.16.2
    chart: rook-ceph
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-cluster
  namespace: argocd
spec:
  destination:
    namespace: rook
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.rook.io/release'
    targetRevision: v1.16.2
    chart: rook-ceph-cluster
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true