apiVersion: v1
kind: Secret
metadata:
  name: rook-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://charts.rook.io/release
  name: rook
  type: helm