apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    namespace: longhorn
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.11
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
