apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: loki-simple-scalable
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.8.11
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
